//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunSimioPortalExpConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://YourSimioPortalURL/")]
        public string URL {
            get {
                return ((string)(this["URL"]));
            }
            set {
                this["URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CreateWebAPITokenAndAddItHere")]
        public string PersonalAccessToken {
            get {
                return ((string)(this["PersonalAccessToken"]));
            }
            set {
                this["PersonalAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RetryResultsIntervalSeconds {
            get {
                return ((int)(this["RetryResultsIntervalSeconds"]));
            }
            set {
                this["RetryResultsIntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int RetryResultsMaxAttempts {
            get {
                return ((int)(this["RetryResultsMaxAttempts"]));
            }
            set {
                this["RetryResultsMaxAttempts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string AuthenticationType {
            get {
                return ((string)(this["AuthenticationType"]));
            }
            set {
                this["AuthenticationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Domain {
            get {
                return ((string)(this["Domain"]));
            }
            set {
                this["Domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchedulingLaborEfficiencies")]
        public string ProjectName {
            get {
                return ((string)(this["ProjectName"]));
            }
            set {
                this["ProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_ModelValues")]
        public string RunSchedulePlanScenarioName {
            get {
                return ((string)(this["RunSchedulePlanScenarioName"]));
            }
            set {
                this["RunSchedulePlanScenarioName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunScheduleControlValuesArray {
            get {
                return ((string)(this["RunScheduleControlValuesArray"]));
            }
            set {
                this["RunScheduleControlValuesArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunSchedule {
            get {
                return ((bool)(this["RunSchedule"]));
            }
            set {
                this["RunSchedule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunScheduleRiskAnalysis {
            get {
                return ((bool)(this["RunScheduleRiskAnalysis"]));
            }
            set {
                this["RunScheduleRiskAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PublishSchduleRun {
            get {
                return ((bool)(this["PublishSchduleRun"]));
            }
            set {
                this["PublishSchduleRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchedRunPub")]
        public string PublishScheduleName {
            get {
                return ((string)(this["PublishScheduleName"]));
            }
            set {
                this["PublishScheduleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchedRunPubDesc")]
        public string PublishScheduleDescription {
            get {
                return ((string)(this["PublishScheduleDescription"]));
            }
            set {
                this["PublishScheduleDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OptQuestRun")]
        public string RunExperimentRunDesc {
            get {
                return ((string)(this["RunExperimentRunDesc"]));
            }
            set {
                this["RunExperimentRunDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{ ""Scenarios"": [{ ""Name"": ""Scenario1"", ""ReplicationsRequired"": 10, ""ControlValues"": [{ ""Name"": ""ToolQty"", ""Value"": 1}]},{ ""Name"": ""Scenario2"", ""ReplicationsRequired"": 10, ""ControlValues"": [{ ""Name"": ""ToolQty"", ""Value"": 2}]},{ ""Name"": ""Scenario3"", ""ReplicationsRequired"": 10, ""ControlValues"": [{ ""Name"": ""ToolQty"", ""Value"": 3}]},{ ""Name"": ""Scenario4"", ""ReplicationsRequired"": 10, ""ControlValues"": [{ ""Name"": ""ToolQty"", ""Value"": 4}]},{ ""Name"": ""Scenario5"", ""ReplicationsRequired"": 10, ""ControlValues"": [{ ""Name"": ""ToolQty"", ""Value"": 5}]}]}")]
        public string RunExperimentScenariosJSON {
            get {
                return ((string)(this["RunExperimentScenariosJSON"]));
            }
            set {
                this["RunExperimentScenariosJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunExperiment {
            get {
                return ((bool)(this["RunExperiment"]));
            }
            set {
                this["RunExperiment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PublishExperimentRun {
            get {
                return ((bool)(this["PublishExperimentRun"]));
            }
            set {
                this["PublishExperimentRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExpPub")]
        public string PublishExperimentRunName {
            get {
                return ((string)(this["PublishExperimentRunName"]));
            }
            set {
                this["PublishExperimentRunName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExpPubDesc")]
        public string PublishExperimetnRunDescription {
            get {
                return ((string)(this["PublishExperimetnRunDescription"]));
            }
            set {
                this["PublishExperimetnRunDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WaitAtEnd {
            get {
                return ((bool)(this["WaitAtEnd"]));
            }
            set {
                this["WaitAtEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int RunLengthDays {
            get {
                return ((int)(this["RunLengthDays"]));
            }
            set {
                this["RunLengthDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportAllTables {
            get {
                return ((bool)(this["ImportAllTables"]));
            }
            set {
                this["ImportAllTables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportAllTablesAndLogs {
            get {
                return ((bool)(this["ExportAllTablesAndLogs"]));
            }
            set {
                this["ExportAllTablesAndLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string StartTimeSelection {
            get {
                return ((string)(this["StartTimeSelection"]));
            }
            set {
                this["StartTimeSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime SpecificStartingTime {
            get {
                return ((global::System.DateTime)(this["SpecificStartingTime"]));
            }
            set {
                this["SpecificStartingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int BearerTokenRefreshIntervalMinutes {
            get {
                return ((int)(this["BearerTokenRefreshIntervalMinutes"]));
            }
            set {
                this["BearerTokenRefreshIntervalMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreatePlanExperimentRunIfNotFound {
            get {
                return ((bool)(this["CreatePlanExperimentRunIfNotFound"]));
            }
            set {
                this["CreatePlanExperimentRunIfNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecreatePlanExperimentRunIfFound {
            get {
                return ((bool)(this["RecreatePlanExperimentRunIfFound"]));
            }
            set {
                this["RecreatePlanExperimentRunIfFound"] = value;
            }
        }
    }
}
